package com.gas.zhihu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gas.zhihu.bean.PaperBean;
import com.gas.zhihu.bean.ExperienceBean;
import com.gas.zhihu.bean.MapBean;

import com.gas.zhihu.db.PaperBeanDao;
import com.gas.zhihu.db.ExperienceBeanDao;
import com.gas.zhihu.db.MapBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig paperBeanDaoConfig;
    private final DaoConfig experienceBeanDaoConfig;
    private final DaoConfig mapBeanDaoConfig;

    private final PaperBeanDao paperBeanDao;
    private final ExperienceBeanDao experienceBeanDao;
    private final MapBeanDao mapBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        paperBeanDaoConfig = daoConfigMap.get(PaperBeanDao.class).clone();
        paperBeanDaoConfig.initIdentityScope(type);

        experienceBeanDaoConfig = daoConfigMap.get(ExperienceBeanDao.class).clone();
        experienceBeanDaoConfig.initIdentityScope(type);

        mapBeanDaoConfig = daoConfigMap.get(MapBeanDao.class).clone();
        mapBeanDaoConfig.initIdentityScope(type);

        paperBeanDao = new PaperBeanDao(paperBeanDaoConfig, this);
        experienceBeanDao = new ExperienceBeanDao(experienceBeanDaoConfig, this);
        mapBeanDao = new MapBeanDao(mapBeanDaoConfig, this);

        registerDao(PaperBean.class, paperBeanDao);
        registerDao(ExperienceBean.class, experienceBeanDao);
        registerDao(MapBean.class, mapBeanDao);
    }
    
    public void clear() {
        paperBeanDaoConfig.clearIdentityScope();
        experienceBeanDaoConfig.clearIdentityScope();
        mapBeanDaoConfig.clearIdentityScope();
    }

    public PaperBeanDao getPaperBeanDao() {
        return paperBeanDao;
    }

    public ExperienceBeanDao getExperienceBeanDao() {
        return experienceBeanDao;
    }

    public MapBeanDao getMapBeanDao() {
        return mapBeanDao;
    }

}
