package com.gas.zhihu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gas.zhihu.bean.MapBean;
import com.gas.zhihu.bean.PaperBean;

import com.gas.zhihu.db.MapBeanDao;
import com.gas.zhihu.db.PaperBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapBeanDaoConfig;
    private final DaoConfig paperBeanDaoConfig;

    private final MapBeanDao mapBeanDao;
    private final PaperBeanDao paperBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapBeanDaoConfig = daoConfigMap.get(MapBeanDao.class).clone();
        mapBeanDaoConfig.initIdentityScope(type);

        paperBeanDaoConfig = daoConfigMap.get(PaperBeanDao.class).clone();
        paperBeanDaoConfig.initIdentityScope(type);

        mapBeanDao = new MapBeanDao(mapBeanDaoConfig, this);
        paperBeanDao = new PaperBeanDao(paperBeanDaoConfig, this);

        registerDao(MapBean.class, mapBeanDao);
        registerDao(PaperBean.class, paperBeanDao);
    }
    
    public void clear() {
        mapBeanDaoConfig.clearIdentityScope();
        paperBeanDaoConfig.clearIdentityScope();
    }

    public MapBeanDao getMapBeanDao() {
        return mapBeanDao;
    }

    public PaperBeanDao getPaperBeanDao() {
        return paperBeanDao;
    }

}
