package com.gas.zhihu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gas.zhihu.bean.MapBean;

import com.gas.zhihu.db.MapBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapBeanDaoConfig;

    private final MapBeanDao mapBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapBeanDaoConfig = daoConfigMap.get(MapBeanDao.class).clone();
        mapBeanDaoConfig.initIdentityScope(type);

        mapBeanDao = new MapBeanDao(mapBeanDaoConfig, this);

        registerDao(MapBean.class, mapBeanDao);
    }
    
    public void clear() {
        mapBeanDaoConfig.clearIdentityScope();
    }

    public MapBeanDao getMapBeanDao() {
        return mapBeanDao;
    }

}
